<?php
/**
 * @category    Trialfire
 * @package     Trialfire_Tracker
 * @author      Mark Lieberman <mark@trialfire.com>
 * @copyright   Copyright (c) Trialfire
 *
 * Render a category view event into the category page.
 */
?>
<script>
require(['Trialfire_Tracker/js/tfMage'], function (tfMage) {
  tfMage.pushEvents([{ 
    $name: 'viewCategory', 
    props: {
      name: '<?= $block->escapeJs($block->getCurrentCategory()->getName()); ?>',
      id: '<?=  $block->escapeJs($block->getCurrentCategory()->getId()); ?>'
    }
  }]);
  tfMage.trackNow();
});
</script>
