<?php
/**
 * @category    Trialfire
 * @package     Trialfire_Tracker
 * @author      Mark Lieberman <mark@trialfire.com>
 * @copyright   Copyright (c) Trialfire
 * 
 * Outputs a tracking script include at the top of every page.
 */
?>
<script type="text/javascript">
var s = document.createElement('script');
s.src = "<?= $block->getAssetUrl(); ?>";
s.onload = function () {
  Trialfire.init('<?= $block->getApiToken(); ?>');
};
document.head.appendChild(s);
</script>
