<?php
/**
 * @category    Trialfire
 * @package     Trialfire_Tracker
 * @author      Mark Lieberman <mark@trialfire.com>
 * @copyright   Copyright (c) Trialfire
 * 
 * Render a product view event into the product page.
 */
?>
<script>
require(['Trialfire_Tracker/js/tfMage'], function (tfMage) {
  tfMage.pushEvents([{ 
    $name: 'viewProduct', 
    productName: '<?= $block->getProduct()->getName(); ?>',
    productId: '<?= $block->getProduct()->getId(); ?>'
  }]);
  tfMage.trackNow();
});
</script>
